CREATE DATABASE BANCO_COMPRA_GADO;
GO
USE BANCO_COMPRA_GADO;

CREATE TABLE PECUARISTA
(
    ID INT IDENTITY(1,1) NOT NULL,
    NOME VARCHAR(40) NOT NULL,
    PRIMARY KEY(ID)
)

CREATE TABLE ANIMAL
(
    ID INT IDENTITY(1,1) NOT NULL,
    DESCRICAO VARCHAR(40) NOT NULL,
    PRECO NUMERIC(15,4) NOT NULL,
    PRIMARY KEY(ID)
)

CREATE TABLE COMPRA_GADO
(
    ID INT IDENTITY(1,1) NOT NULL,
    DATA_ENTREGA DATETIME NOT NULL,
    PECUARISTA_ID INT NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(PECUARISTA_ID) REFERENCES PECUARISTA(ID)
)

CREATE TABLE COMPRA_GADO_ITEM
(
    ID INT IDENTITY(1,1) NOT NULL,
    QUANTIDADE INT NOT NULL,
    COMPRA_GADO_ID INT NOT NULL,
    ANIMAL_ID INT NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(COMPRA_GADO_ID) REFERENCES COMPRA_GADO(ID),
    FOREIGN KEY(ANIMAL_ID) REFERENCES ANIMAL(ID)
)

INSERT INTO ANIMAL(DESCRICAO, PRECO) VALUES ('BOI', 1600)
INSERT INTO ANIMAL(DESCRICAO, PRECO) VALUES ('VACA', 1500)

INSERT INTO PECUARISTA(NOME) VALUES ('PECUARISTA 1')
INSERT INTO PECUARISTA(NOME) VALUES ('PECUARISTA 2')